### ISSUE TITLE
Updates for sightglass to target portability and plugin features

### ISSUE THREAD

**Issue by jlb6740** [fastly/sightglass#5]
@jedisct1  @pchickey @sunfishcode

Hi,

Having had some interest in surveying the performance of various standalone WASM VMs, I've made several updates to sightglass that I am thinking should be useful as a contribution. In my updates are here:
- https://github.com/jlb6740/sightglass/tree/sightglass_runner
- https://github.com/jlb6740/sightglass/tree/sightglass_webui

I've explicitly split the runner and the UI in master into different projects. One of the reasons for this is that I've also containerized each component so that they can be installed and used independently. In addition to the logical separations and container feature, there are several updates that should be useful:

1. The runner portion is now plugin based and automated for the combination of VMs and workloads. What this means is that you add a script that defines how to check out and compile a VM and the framework will automatically call this script before running a test suite. It also means that there is a separate script that defines how to build for a particular workload suite and the framework will automatically call this script as well when needed.

2. I've added script support for lucet and wasmtime but other VMs including (node, wamr, etc) can be plugged in as well. So instead of adding sightglass to lucet, lucet is added to sightglass and updated (and the same for all the other VMs)

3. Also added polybench http://web.cse.ohio-state.edu/~pouchet.2/software/polybench/ which currently runs for wasmtime_app and lucet_app

4. Added a driver to make running everything simple. In particular it is possible to send results from the sightglass_runner to the server running the sightglass_viewer.

5. Added a viewer for sightglass_runner to see results immediately without needing to send to server running sightglass_viewer which is really intended to track history.

To get started with sightglass_runner, build the container and run a command through the driver, i.e.:
 
`./sg_container_build.sh`
`./sg_container_runner.sh --help`
or
`./sg_container_runner.sh -r lucet_app -p shootout`

To get started with sightglass_ui, build the container and launch the containerized web-server

`./sg_webui_build.sh`
`./sg_webui_run.sh`

I'd like some feedback on this, but I have found sightglass to be useful, I've found these changes to be useful and I am thinking this contributions could either be contributed back to sightglass as separate branches or, more preferred ... folded into the cranestation project https://github.com/CraneStation since there is more visibility here and this would be useful for all projects that depend on cranestation and wasi.

**Comment by jedisct1** [comment]
Hi Johnnie,

This is really nice! And I'm glad you found sightlass useful!

Currently, sightglass is a general-purpose tool, which can be useful to compare multiple implementations of the same functions, different compiler optimizations, on different operating systems.

And maybe it would be best to keep it portable, generic, and something that can simply be installed with `cargo install` instead of requiring Docker and tying it to a specific use case.

The "benchmarks" directory is actually what could be moved to a different repository. These are just examples of what sightglass can be used with.

Comparing different WebAssembly runtimes (+ code generators, e.g. singlepass/cranelift/LLVM for wasmer) is interesting, but should probably be a project of its own, importing sightglass instead of extending it.

**Comment by jlb6740** [comment]
@jedisct1 Cool .. thanks for the feedback. I agree the additions are such that it makes sense for this to be project on its on that is targeting WASM VMs. I'll put these branches somewhere. In addition to adding more VMs and benchmarks there are few more features such as (1) tools that support recording performance of benchmarks that report scores or metrics other than elapsed time, or (2) the ability parameterize the webui or (3) adding support multiple suites through a single webui, that may or may not fit here under this baseline sightglass that I'd like to the current updates here.

**Comment by jedisct1** [comment]
These improvements look very promising! 👍
